### ISSUE TITLE
Feature sugestion: return html report without saving to file

### ISSUE THREAD

**Issue by carlosvega** [matthiaskoenig/sbmlutils#144]
The report functionality is great, but, so that it could be served by a flask or django served, it would be great to be able to store the generated HTML into a variable without writing it to a file.

**Comment by matthiaskoenig** [comment]
@sankha555 This issue is also not too much work and would improve the existing report.

**Comment by sankha555** [comment]
Sure, I will start working on this issue today afternoon and try to come up with a pull request for it. Thanks!
