### ISSUE TITLE
Add set of curated biomodels as test suite for the report generation

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#199]
Add a parametrized pytest which allows to create the report with all curated biomodels.
- [ ] download the latest curated biomodels and add to `test/data/models/biomodels_curated/`
- [ ] create parametrized tests using these ~1000 models to create the report

@sankha555 These models should all pass the report generation with the new and old math. This would give you additional test cases and show possible problems.

**Comment by sankha555** [comment]
@matthiaskoenig I would surely add the models and create the test for them. I suppose that I have to download these models from an external source, could you please help me with the link for the repository or the website from where I should download these models. I would start creating the tests as soon as I download the models. Thanks!

**Comment by matthiaskoenig** [comment]
You can download the curated models from biomodels 
https://www.ebi.ac.uk/biomodels/search?offset=0&numResults=100&sort=relevance-desc&query=*%3A*+AND+curationstatus%3A%22Manually+curated%22&domain=biomodels
I think you have to go through the 10 pages to download the ~1000 curated models.
