### ISSUE TITLE
Prototype of vue.js interactive JSON rendering for reports

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#226]
This is for the evaluation of technology for the new reporting system. A minimal working example would be: Single HTML page with vue.js included which can render JSON provided in the HTML as `<script>` information or a separate file.

**Comment by sankha555** [comment]
@matthiaskoenig I have made a basic outline for the minimal prototype. Please take a look at it and let me know what changes I should incorporate in it. I have written the outline in the following Google Doc:

https://docs.google.com/document/d/1pxFk4h2iNicmIj_3xVFZj3QgMnJc7_U-pvt30AQZuks/edit?usp=sharing

Looking forward to your feedback and reviews on this Sir. I would make the required changes according to your suggestions and try to improve it. Thanks!

**Comment by matthiaskoenig** [comment]
The outline reads good. I would start with a minimal example of rendering some JSON. For me the most important thing is how this is working and how complicated it is to make the individual pieces work together. Not important to have real content, just to see if this is working at all and will allow easy development of the report.

**Comment by sankha555** [comment]
@matthiaskoenig Thanks a lot for the feedback Sir. In that case, I would make a test HTML file with some representative JSON content to view on it. I would upload this file as a part of a pull request for your review. Once the testing phase is complete, we can remove the file and test with real SBML models perhaps. Also, if I should make the first test using some specific JSON example, please let me know, I would make the tests with them. Thanks!

**Comment by sankha555** [comment]
Sure Sir, I would initiate the vue project in the root and start working and testing through the vue-cli. Will come up with a patch for your review soon on this. Thanks!
