### ISSUE TITLE
Incorrect handling of id/variable/symbol in Rules and InitialAssignments in report

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#297]
What is the `id` in the rules is in reality the `variable`, what is the `id` in the InitialAssignments is the `symbol`. This is incorrect in the backend and incorrect rendered in the frontend. E.g. `glucose` example. Have a look at the `XML` to see the correct attributes. The rules and initial assignments do not have ids here (but in principle could).

@sankha555 I will fix the backend, can you update the frontend.

**Comment by sankha555** [comment]
Sure Sir, once you are done with the backend changes, please tag me again here, and I will update the frontend accordingly.

**Comment by matthiaskoenig** [comment]
@sankha555 just added the backend fixes. You have to add variable/symbol to rules/initialAssignments tables and detailView, respectively.

**Comment by sankha555** [comment]
Fixed in latest commit 66a70c42
