### ISSUE TITLE
Feature to download component wise JSON and XML

### ISSUE THREAD

**Issue by sankha555** [matthiaskoenig/sbmlutils#385]
Perhaps we can add a feature to download the JSON and XML content for each individual component in a model. Currently one can only access these contents in the detail view.

The feature may also be extended to downloading JSON and XML for the entire report (especially useful if the report is generated from a URL).

Please let me know what you think about this feature.

**Comment by matthiaskoenig** [comment]
Thanks for the idea. Currently not a priority.
