### ISSUE TITLE
Drag and Drop non-functional

### ISSUE THREAD

**Issue by Lepujolh** [matthiaskoenig/sbmlutils#386]
#### Problem description

Please explain: 

When dropping only one file, the following error message shows up: 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/92518503/144272750-c49c3d4f-776f-4298-8fd9-f8df31e9d611.png">

**Comment by matthiaskoenig** [comment]
This happens if you removed a file from the list before. Just reload the page and drop the file again will solve the issue.
