### ISSUE TITLE
How to include scientific e-notation (e.g 2 * 10^-5) for parameter values?

### ISSUE THREAD

**Issue by alifarhat40** [matthiaskoenig/sbmlutils#414]
### Checklist

- [x] I searched the [documentation](https://sbmlutils.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/matthiaskoenig/sbmlutils/issues).

### Question

Hello, I am currently writing XML files and searched through all the documentation, but I am unable to find a solution. The question is how do I write the following "`<parameter id="k1" value="2*10^-5">`" ?? All the documentation lists value to be just one decimal number, but is this really the best way? Should I do value = "0.00002" ? Sometimes there may be tens of zeros. I only found the following: `<cn type="e-notation"> 2 <sep/> -5 </cn>`  . However, I do not know how to put this in the value. Any help is appreiated.

**Comment by matthiaskoenig** [comment]
Hi @alifarhat40,
thanks for the question.

You can just simple write `value=2E-5`. Here is an example

```python
Parameter(
    "p2", 2E-5, U.mg,
    notes="""
    Constant parameter with value in E notation.
    """
)
```

```xml
 <parameter id="p2" value="2e-05" units="mg" constant="true">
  <notes>
    <body xmlns="http://www.w3.org/1999/xhtml">
      <p>Constant parameter with value in E notation.</p>
    </body>
  </notes>
</parameter>
```

I create a full example in the following describing the parameter syntax better.
https://github.com/matthiaskoenig/sbmlutils/commit/3e18ebcbacd643f64ea1c2def70fcc6dd1b11f31
I am currently in the process of updating the documentation for the model factory, so things should be clearer shortly.
If you have more questions just let me know.

Best Matthias
