### ISSUE TITLE
Not parsing character codes in ontology links?

### ISSUE THREAD

**Issue by jpsluka** [matthiaskoenig/sbmlutils#432]
#### Problem description

Please explain:
If an annotation has character codes in the ontology ID then you get an error. For example, in the SBML:
        <annotation>
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqmodel="http://biomodels.net/model-qualifiers/" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#_ee25db80-7f20-406d-8b04-c9fa5f27256b">
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/chebi/**CHEBI%3A29132"**/>
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </annotation>

Note the CHEBI id is given as "CHEBI%3A29132" and the %3A is ":".
This gives an error
![CharacterCode](https://user-images.githubusercontent.com/22944062/215877003-55b4522f-7efa-4688-a2a2-d02a65789aa7.png)

But SBML4Humans is still also listing the correct info for CHEBI:29132
#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
```

```
```

### Context

<details>

```
```

</details>

**Comment by matthiaskoenig** [comment]
Hi @jpsluka,

thanks for the report. Can you share the SBML model then I can fix the issue asap.
It is much easier to debug with the actual model which shows the issue.

Where do you see the issue? I assume in the https://sbml4humans.de frontend?

Best Matthias

**Comment by jpsluka** [comment]
Mathias-
Yes, this was on the sbml4humans.de web page.
Thanks
Jim

James P. Sluka, PhD
Biocomplexity Institute
Intelligent Systems Engineering
School of Informatics, Computing and Engineering
Indiana University
Bloomington, IN   USA
Office: 812-855-2441
Cell: 317-331-7465

**Comment by matthiaskoenig** [comment]
Hi @jpsluka, 
sorry for the long delay. Working on the updates at the moment and will make this more robust. I.e. accepting the escaped characters and only create a warning.

But I think your identifiers are just incorrect. See for instance on identifiers.org if you try to put the identifier in you will get similar errors. Most tools will do the identical implementation as me and identifiers.org and check that the regular expressions are matching. Having to handle the escaped identifiers in every tool will not work.
There is a clear definition of the regular expression which has to be matched.
![Screenshot from 2023-10-09 13-43-29](https://github.com/matthiaskoenig/sbmlutils/assets/900538/f4304b91-5236-4c79-909a-91fe0858ed9c)

https://registry.identifiers.org/registry/chebi
Local Unique Identifier (LUI) pattern: ^CHEBI:\d+$

So I would definitely update the identifiers in your model.

**Comment by jpsluka** [comment]
But the **URL** http://identifiers.org/chebi/CHEBI%3A29132 does work.

So I think the challenge is when a URI is a URL and URL rules are applied in a document. Many editors will replace special characters (like :) in URLs.

This is just one of the complexities that arise when a large number of tools are used to create documents.

I would understand though if you think this is out of scope for sbmlutils.

**Comment by matthiaskoenig** [comment]
This has been fixed. Will be online as soon as I deploy the new version.
