### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by shoepfl** [matthiaskoenig/sbmlutils#434]
Hi Matthias,

currently I get a pydantic error, when using sbmlutils 0.8.4:

UserWarning: Field "model_units" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/basti/miniconda3/envs/sbmlutils/lib/python3.11/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_definitions" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
───────────────────────────────────────────────────────────────────────────────────── Create SBML ──────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/mnt/c/Users/basti/Documents/Uni/11_Doktorarbeit/Python/BayModTS/test.py", line 74, in <module>
    results = create_model(
              ^^^^^^^^^^^^^
  File "/home/basti/miniconda3/envs/sbmlutils/lib/python3.11/site-packages/sbmlutils/factory.py", line 3619, in create_model
    m = Model.merge_models(model)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/basti/miniconda3/envs/sbmlutils/lib/python3.11/site-packages/sbmlutils/factory.py", line 3445, in merge_models
    kind = m2._keys.get(key, None)
           ^^^^^^^^
  File "/home/basti/miniconda3/envs/sbmlutils/lib/python3.11/site-packages/pydantic/main.py", line 711, in __getattr__
    return self.__pydantic_private__[item]  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/basti/miniconda3/envs/sbmlutils/lib/python3.11/site-packages/pydantic/main.py", line 715, in __getattr__
    pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Model' object has no attribute '__pydantic_extra__'. Did you mean: '__pydantic_complete__'?

The error occours now in the file I already sent you for the RTD function: 
[test.py.txt](https://github.com/matthiaskoenig/sbmlutils/files/12226995/test.py.txt)

for me this seems to be a problem with my dependencies - can you help me here?

Thanks, Sebastian

**Comment by matthiaskoenig** [comment]
Hi @shoepfl,
this is most likely due to the latest pydantic release. Downgrading pydantic to <2.0 should fix this.
I will provide a bugfix asap.
Best Matthias

**Comment by shoepfl** [comment]
Thanks @matthiaskoenig,

i succeeded with pydantic 1.10.2

Best,
Sebastian

**Comment by harveymannering** [comment]
We also had this issue, which was causing [tests to fail](https://github.com/combine-org/combine-notebooks/actions/runs/5737825746/job/15550199465#step:5:95).  We fixed this by downgrading pydantic to <2.0.

**Comment by matthiaskoenig** [comment]
This is fixed in the latest version 0.8.5
