### ISSUE TITLE
sbml4humans api unresponsive

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#442]
- check server configuration, probably docker containers didn't restart correctly

**Comment by jpsluka** [comment]
https://sbml4humans.de/ still does not seem to respond. I tried uploading via drag-drop, file upload and pasting SBML but it seems to get stuck at the "Creating SBML report" and never seems to return.

**Comment by matthiaskoenig** [comment]
Figured out what is happening and will fix this during the day.

**Comment by matthiaskoenig** [comment]
Finally fixed.
